### ISSUE TITLE
ENH: compute_mash_distances updating progress bar for parallel execution

### ISSUE THREAD

**Issue by GavinHuttley** [HuttleyLab/DiverseSeq#54]
Inside the `for future in futures` loop add
```python
        if self._with_progress:
            self._progress.update(distance_task, advance=1, refresh=True)
```

**Comment by rmcar17** [comment]
I gave this a go, and the way the chunks are distributed makes it seem to a user like it's hanging without any progress (until they later all come in at approximately the same type). I think it may be best to keep the current spinner-like bar.
